// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/fetcher/fetcher.proto

package fetcher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Fetcher service

func NewFetcherEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Fetcher service

type FetcherService interface {
	FetchRaw(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	QueryRaw(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type fetcherService struct {
	c    client.Client
	name string
}

func NewFetcherService(name string, c client.Client) FetcherService {
	return &fetcherService{
		c:    c,
		name: name,
	}
}

func (c *fetcherService) FetchRaw(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Fetcher.FetchRaw", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetcherService) QueryRaw(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Fetcher.QueryRaw", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fetcher service

type FetcherHandler interface {
	FetchRaw(context.Context, *Request, *Response) error
	QueryRaw(context.Context, *Request, *Response) error
}

func RegisterFetcherHandler(s server.Server, hdlr FetcherHandler, opts ...server.HandlerOption) error {
	type fetcher interface {
		FetchRaw(ctx context.Context, in *Request, out *Response) error
		QueryRaw(ctx context.Context, in *Request, out *Response) error
	}
	type Fetcher struct {
		fetcher
	}
	h := &fetcherHandler{hdlr}
	return s.Handle(s.NewHandler(&Fetcher{h}, opts...))
}

type fetcherHandler struct {
	FetcherHandler
}

func (h *fetcherHandler) FetchRaw(ctx context.Context, in *Request, out *Response) error {
	return h.FetcherHandler.FetchRaw(ctx, in, out)
}

func (h *fetcherHandler) QueryRaw(ctx context.Context, in *Request, out *Response) error {
	return h.FetcherHandler.QueryRaw(ctx, in, out)
}
