// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: proto/processor/processor.proto

package processor

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag       string `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Body       string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	UpdateTime int64  `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Stock) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Stock) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date     string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	FlagName string `protobuf:"bytes,2,opt,name=flagName,proto3" json:"flagName,omitempty"`
	Params   int32  `protobuf:"varint,3,opt,name=params,proto3" json:"params,omitempty"` //	0 - send to process; 1 - return
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Request) GetFlagName() string {
	if x != nil {
		return x.FlagName
	}
	return ""
}

func (x *Request) GetParams() int32 {
	if x != nil {
		return x.Params
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StockList []*Stock `protobuf:"bytes,2,rep,name=stockList,proto3" json:"stockList,omitempty"`
	Error     *Error   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetStockList() []*Stock {
	if x != nil {
		return x.StockList
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RegexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginPath string `protobuf:"bytes,1,opt,name=pluginPath,proto3" json:"pluginPath,omitempty"`
	TestStr    string `protobuf:"bytes,2,opt,name=testStr,proto3" json:"testStr,omitempty"`
}

func (x *RegexReq) Reset() {
	*x = RegexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexReq) ProtoMessage() {}

func (x *RegexReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexReq.ProtoReflect.Descriptor instead.
func (*RegexReq) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{4}
}

func (x *RegexReq) GetPluginPath() string {
	if x != nil {
		return x.PluginPath
	}
	return ""
}

func (x *RegexReq) GetTestStr() string {
	if x != nil {
		return x.TestStr
	}
	return ""
}

type RegexRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResStr string `protobuf:"bytes,1,opt,name=resStr,proto3" json:"resStr,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *RegexRsp) Reset() {
	*x = RegexRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegexRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexRsp) ProtoMessage() {}

func (x *RegexRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexRsp.ProtoReflect.Descriptor instead.
func (*RegexRsp) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{5}
}

func (x *RegexRsp) GetResStr() string {
	if x != nil {
		return x.ResStr
	}
	return ""
}

func (x *RegexRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type BuildSoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginPath string `protobuf:"bytes,1,opt,name=pluginPath,proto3" json:"pluginPath,omitempty"`
	SourceCode string `protobuf:"bytes,2,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
}

func (x *BuildSoReq) Reset() {
	*x = BuildSoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildSoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSoReq) ProtoMessage() {}

func (x *BuildSoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSoReq.ProtoReflect.Descriptor instead.
func (*BuildSoReq) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{6}
}

func (x *BuildSoReq) GetPluginPath() string {
	if x != nil {
		return x.PluginPath
	}
	return ""
}

func (x *BuildSoReq) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type BuildSoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg string `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *BuildSoRsp) Reset() {
	*x = BuildSoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildSoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSoRsp) ProtoMessage() {}

func (x *BuildSoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSoRsp.ProtoReflect.Descriptor instead.
func (*BuildSoRsp) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{7}
}

func (x *BuildSoRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *BuildSoRsp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetSourceCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetSourceCodeReq) Reset() {
	*x = GetSourceCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSourceCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceCodeReq) ProtoMessage() {}

func (x *GetSourceCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceCodeReq.ProtoReflect.Descriptor instead.
func (*GetSourceCodeReq) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{8}
}

func (x *GetSourceCodeReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetSourceCodeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg     string `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SourceCode string `protobuf:"bytes,2,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
}

func (x *GetSourceCodeRsp) Reset() {
	*x = GetSourceCodeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSourceCodeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceCodeRsp) ProtoMessage() {}

func (x *GetSourceCodeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceCodeRsp.ProtoReflect.Descriptor instead.
func (*GetSourceCodeRsp) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{9}
}

func (x *GetSourceCodeRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetSourceCodeRsp) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

type GetPluginPathReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginPathReq) Reset() {
	*x = GetPluginPathReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginPathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginPathReq) ProtoMessage() {}

func (x *GetPluginPathReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginPathReq.ProtoReflect.Descriptor instead.
func (*GetPluginPathReq) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{10}
}

type GetPluginPathRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrMsg     string `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	JoinedPath string `protobuf:"bytes,2,opt,name=joinedPath,proto3" json:"joinedPath,omitempty"`
}

func (x *GetPluginPathRsp) Reset() {
	*x = GetPluginPathRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_processor_processor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginPathRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginPathRsp) ProtoMessage() {}

func (x *GetPluginPathRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_processor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginPathRsp.ProtoReflect.Descriptor instead.
func (*GetPluginPathRsp) Descriptor() ([]byte, []int) {
	return file_proto_processor_processor_proto_rawDescGZIP(), []int{11}
}

func (x *GetPluginPathRsp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetPluginPathRsp) GetJoinedPath() string {
	if x != nil {
		return x.JoinedPath
	}
	return ""
}

var File_proto_processor_processor_proto protoreflect.FileDescriptor

var file_proto_processor_processor_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e,
	0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x22, 0x77, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x61,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6c, 0x61,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x33, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0xa6, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73,
	0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e,
	0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30,
	0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53,
	0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74,
	0x72, 0x22, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x53, 0x74, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x4c, 0x0a,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x53, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x4a, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x22, 0x4a, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x6a, 0x6f, 0x69,
	0x6e, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6a,
	0x6f, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x32, 0xa1, 0x04, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x5e, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x27, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32,
	0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x69,
	0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x65, 0x78,
	0x54, 0x65, 0x73, 0x74, 0x12, 0x28, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67,
	0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x28,
	0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31,
	0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x07, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x53, 0x6f, 0x12, 0x2a, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e,
	0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x2a, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33,
	0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x6f, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x75, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x30, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e,
	0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x30, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32,
	0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x30, 0x2e, 0x73, 0x69, 0x64, 0x61, 0x7a, 0x68,
	0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x30, 0x2e, 0x73, 0x69, 0x64, 0x61,
	0x7a, 0x68, 0x61, 0x6e, 0x67, 0x31, 0x32, 0x33, 0x2e, 0x66, 0x31, 0x30, 0x2e, 0x73, 0x72, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_processor_processor_proto_rawDescOnce sync.Once
	file_proto_processor_processor_proto_rawDescData = file_proto_processor_processor_proto_rawDesc
)

func file_proto_processor_processor_proto_rawDescGZIP() []byte {
	file_proto_processor_processor_proto_rawDescOnce.Do(func() {
		file_proto_processor_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_processor_processor_proto_rawDescData)
	})
	return file_proto_processor_processor_proto_rawDescData
}

var file_proto_processor_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_processor_processor_proto_goTypes = []interface{}{
	(*Stock)(nil),            // 0: sidazhang123.f10.srv.processor.Stock
	(*Request)(nil),          // 1: sidazhang123.f10.srv.processor.Request
	(*Error)(nil),            // 2: sidazhang123.f10.srv.processor.Error
	(*Response)(nil),         // 3: sidazhang123.f10.srv.processor.Response
	(*RegexReq)(nil),         // 4: sidazhang123.f10.srv.processor.RegexReq
	(*RegexRsp)(nil),         // 5: sidazhang123.f10.srv.processor.RegexRsp
	(*BuildSoReq)(nil),       // 6: sidazhang123.f10.srv.processor.BuildSoReq
	(*BuildSoRsp)(nil),       // 7: sidazhang123.f10.srv.processor.BuildSoRsp
	(*GetSourceCodeReq)(nil), // 8: sidazhang123.f10.srv.processor.GetSourceCodeReq
	(*GetSourceCodeRsp)(nil), // 9: sidazhang123.f10.srv.processor.GetSourceCodeRsp
	(*GetPluginPathReq)(nil), // 10: sidazhang123.f10.srv.processor.GetPluginPathReq
	(*GetPluginPathRsp)(nil), // 11: sidazhang123.f10.srv.processor.GetPluginPathRsp
}
var file_proto_processor_processor_proto_depIdxs = []int32{
	0,  // 0: sidazhang123.f10.srv.processor.Response.stockList:type_name -> sidazhang123.f10.srv.processor.Stock
	2,  // 1: sidazhang123.f10.srv.processor.Response.error:type_name -> sidazhang123.f10.srv.processor.Error
	1,  // 2: sidazhang123.f10.srv.processor.Processor.Process:input_type -> sidazhang123.f10.srv.processor.Request
	4,  // 3: sidazhang123.f10.srv.processor.Processor.RegexTest:input_type -> sidazhang123.f10.srv.processor.RegexReq
	6,  // 4: sidazhang123.f10.srv.processor.Processor.BuildSo:input_type -> sidazhang123.f10.srv.processor.BuildSoReq
	8,  // 5: sidazhang123.f10.srv.processor.Processor.GetSourceCode:input_type -> sidazhang123.f10.srv.processor.GetSourceCodeReq
	10, // 6: sidazhang123.f10.srv.processor.Processor.GetPluginPath:input_type -> sidazhang123.f10.srv.processor.GetPluginPathReq
	3,  // 7: sidazhang123.f10.srv.processor.Processor.Process:output_type -> sidazhang123.f10.srv.processor.Response
	5,  // 8: sidazhang123.f10.srv.processor.Processor.RegexTest:output_type -> sidazhang123.f10.srv.processor.RegexRsp
	7,  // 9: sidazhang123.f10.srv.processor.Processor.BuildSo:output_type -> sidazhang123.f10.srv.processor.BuildSoRsp
	9,  // 10: sidazhang123.f10.srv.processor.Processor.GetSourceCode:output_type -> sidazhang123.f10.srv.processor.GetSourceCodeRsp
	11, // 11: sidazhang123.f10.srv.processor.Processor.GetPluginPath:output_type -> sidazhang123.f10.srv.processor.GetPluginPathRsp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_processor_processor_proto_init() }
func file_proto_processor_processor_proto_init() {
	if File_proto_processor_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_processor_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegexRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildSoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildSoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSourceCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSourceCodeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginPathReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_processor_processor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginPathRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_processor_processor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_processor_processor_proto_goTypes,
		DependencyIndexes: file_proto_processor_processor_proto_depIdxs,
		MessageInfos:      file_proto_processor_processor_proto_msgTypes,
	}.Build()
	File_proto_processor_processor_proto = out.File
	file_proto_processor_processor_proto_rawDesc = nil
	file_proto_processor_processor_proto_goTypes = nil
	file_proto_processor_processor_proto_depIdxs = nil
}
